### ISSUE TITLE
Initial bundling during 'katapult new $projectname' uses wrong ruby version

### ISSUE THREAD

**Issue by judithroth** [makandra/katapult#4]
If you run katapult inside an ruby version which is different from 2.3.0 (which is the current default for a new project with katapult) the inital bundling will be done in this ruby version instead of 2.3.0. 
Workaround: Make sure you use ruby 2.3.0 before running `katapult new`.

**Comment by codener** [comment]
Thanks for reporting this! The issue will be solved in 0.3.0 where Katapult asks you which Ruby version you want to use.
